
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?postOwner=675063ff82f983bbbce757e8

###

# GET http://localhost:3000/posts/674088366365996d79acfdd2

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Amazing Post here",
    "owner": "675063ff82f983bbbce757e8",
    "content": "It will surely work"
}

###

# PUT http://localhost:3000/posts/674088366365996d79acfdd2
# Content-Type: application/json

# {
#     "title": "New and amazing post",
#     "owner": "tomer22",
#     "content": "Very good job"
# }

# ###

# GET http://localhost:3000/comments

# ###

# GET http://localhost:3000/comments?user=yoel

# ###

# GET http://localhost:3000/comments/6740902515e5bdf0e3363dcb

# ###

# GET http://localhost:3000/comments/post/674088366365996d79acfdd2

# ###

# POST http://localhost:3000/comments
# Content-Type: application/json

# {
#     "user": "yoel2",
#     "content": "bla bla bla",
#     "postId": "674088366365996d79acfdd2"
# }

# ###

# PUT http://localhost:3000/comments/6740902515e5bdf0e3363dcb
# Content-Type: application/json

# {
#     "content": "content post updating now"
# }

# ###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzUwNzZjYTY0ZGRkMDNkNTM3YjY1ZDIiLCJ1c2VybmFtZSI6InJvbmFydWNoIiwicGFzc3dvcmQiOiIxMjM0NSIsImVtYWlsIjoiMTIzNDUiLCJpYXQiOjE3MzMzMjY5MzIsImV4cCI6MTczMzMyNzIzMn0.TIoX35p7wcMpA5neBfRSf6tKkCH3bKNJJ_3IV-NYhd8

###

GET http://localhost:3000/users/675063ff82f983bbbce757e8

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "tomerelk",
    "password": "123imking",
    "email": "tomerelkm@gmail.com"
}

###

PUT http://localhost:3000/users/675063b982f983bbbce757e3
Content-Type: application/json

{
    "username": "tomerelk",
    "password": "123imking2",
    "email": "tomerelkm@gmail.com"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "joel",
    "password": "12345",
    "email": "joel123@gmail.com"
}

###

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "password": "12345",
    "email": "joel123@gmail.com"
}

###
